#!/bin/sh
exec /usr/osxcross/bin/o64-clang -mmacosx-version-min=10.13 -target x86_64-apple-darwin17 -mlinker-version=242 -B /usr/x86_64-apple-darwin17/bin -isysroot /usr/osxcross/SDK/MacOSX10.13.sdk $*
